import Product from '../models/Product.js';
import Notification from '../models/Notification.js';
import Reservation from '../models/Reservation.js';

// @desc    Fetch all active products
// @route   GET /api/products
// @access  Public
const getProducts = async (req, res) => {
  try {
    const products = await Product.find({ status: 'active' });
    res.json(products);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Fetch a single product by ID
// @route   GET /api/products/:id
// @access  Public
const getProductById = async (req, res) => {
  try {
    const product = await Product.findOne({ id: req.params.id });
    if (product) {
      res.json(product);
    } else {
      res.status(404).json({ message: 'Product not found' });
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Create a new product
// @route   POST /api/products
// @access  Private/Admin
const createProduct = async (req, res) => {
  const { name, description, price, imageUrls, category, stock } = req.body;

  // Basic validation
  if (!name || !price || !category) {
    return res.status(400).json({ message: 'Name, price, and category are required' });
  }

  try {
    const newProduct = new Product({
      // id will be generated by Mongoose based on schema definition
      name,
      description,
      price,
      imageUrls,
      category,
      stock,
    });

    const createdProduct = await newProduct.save();
    res.status(201).json(createdProduct);
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
};

// @desc    Update an existing product
// @route   PUT /api/products/:id
// @access  Private/Admin
const updateProduct = async (req, res) => {
  const { name, description, price, imageUrls, category, stock, status } = req.body;

  try {
    const product = await Product.findOne({ id: req.params.id });

    if (product) {
      const wasOutOfStock = product.stock <= 0;
      product.name = name || product.name;
      product.description = description || product.description;
      product.price = price || product.price;
      product.imageUrls = imageUrls || product.imageUrls;
      product.category = category || product.category;
      product.stock = stock !== undefined ? stock : product.stock;
      product.status = status || product.status;

      const updatedProduct = await product.save();

      // If product was out of stock and now has stock, create notifications
      if (wasOutOfStock && updatedProduct.stock > 0) {
        try {
          // Find users who reserved this product
          const reservations = await Reservation.find({ productId: product.id });
          for (const reservation of reservations) {
            const notification = new Notification({
              userId: reservation.userId,
              productId: product.id,
              message: `Le produit ${product.name} est de nouveau en stock!`,
              read: false,
              date: new Date().toISOString(),
            });
            await notification.save();
          }
        } catch (notificationError) {
          console.error('Error creating notifications:', notificationError);
          // Don't fail the product update if notification creation fails
        }
      }

      res.json(updatedProduct);
    } else {
      res.status(404).json({ message: 'Product not found' });
    }
  } catch (error) {
    res.status(400).json({ message: error.message });
  }
};

// @desc    Soft delete a product (set status to 'deleted')
// @route   DELETE /api/products/:id
// @access  Private/Admin
const deleteProduct = async (req, res) => {
  try {
    const product = await Product.findOne({ id: req.params.id });

    if (product) {
      product.status = 'deleted';
      await product.save();
      res.json({ message: 'Product soft deleted' });
    } else {
      res.status(404).json({ message: 'Product not found' });
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Restore a deleted product (set status to 'active')
// @route   PUT /api/products/:id/restore
// @access  Private/Admin
const restoreProduct = async (req, res) => {
  try {
    const product = await Product.findOne({ id: req.params.id });

    if (product) {
      product.status = 'active';
      await product.save();
      res.json({ message: 'Product restored' });
    } else {
      res.status(404).json({ message: 'Product not found' });
    }
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};


// @desc    Permanently delete a product
// @route   DELETE /api/products/:id/permanent
// @access  Private/Admin
const permanentlyDeleteProduct = async (req, res) => {
    try {
      const result = await Product.deleteOne({ id: req.params.id });

      if (result.deletedCount > 0) {
        res.json({ message: 'Product permanently deleted' });
      } else {
        res.status(404).json({ message: 'Product not found' });
      }
    } catch (error) {
      res.status(500).json({ message: error.message });
    }
  };


export {
  getProducts,
  getProductById,
  createProduct,
  updateProduct,
  deleteProduct,
  restoreProduct,
  permanentlyDeleteProduct,
};